.eslintrc.json
index.html
package-lock.json
package.json
src/main.js
src/sub-module.js

Added ESLint to the component library.

chore: added ESlint.

---

lerna.json
package.json

Chore: Addes larna to component library.

---

packages/opc-styles/.gitignore
packages/opc-styles/README.md
packages/opc-styles/_typography.scss
packages/opc-styles/functions/_custom-properties.scss
packages/opc-styles/functions/_tools.scss
packages/opc-styles/maps/_colors.scss
packages/opc-styles/opc-styles.scss
packages/opc-styles/package-lock.json
packages/opc-styles/package.json
packages/opc-styles/test/playground.scss
packages/opc-styles/variables/_1-definitions.scss
packages/opc-styles/variables/_2-crayons.scss

✅ All functions are tested in run-time

Addes colors with mapped to css custom properties

---

.github/PULL_REQUEST_TEMPLATE.md

Added chrome and mozilla in PR template
No

fix(#17) - Add latest browser support for Chrome and firefox in the PR template 

---

.github/workflows/notify.yml

Added Notifications to One Platform Developers channel when a pull request is opened

chore: Added Gchat Channel Notifications

---

packages/opc-styles/README.md
packages/opc-styles/package.json

and added the public config to the package.json file.
No

Addes the public config to package.json file and updated the @import line in  README.md file

---

generator/generator-opc-generator/package-lock.json
generator/generator-opc-generator/package.json

Minor Version bump for generator
No

fix(#24) - Bump up the version for generator 

---

.github/workflows/notify-fork.yml
.github/workflows/notify-main.yml

fix: Re-enable notification for prs from main repo branches

fix: Re-enable notification for prs from main repo branches

---

packages/opc-styles/package.json
packages/opc-styles/typography/_base.scss

Remove the @import for the font.

removes the red hat font from the opc-style.

---

.github/workflows/notify-fork.yml
.github/workflows/notify-main.yml

chore: using github.event.pull_request.head.repo.full_name to detect forks

chore: using github.event.pull_request.head.repo.full_name

---

packages/opc-styles/README.md
packages/opc-styles/package.json
packages/opc-styles/typography/_base.scss
packages/opc-styles/variables/_1-definitions.scss

Added the Small, Medium and Large Space variables to the opc-styles
No

Added the Gap and Space variables for the opc-styles.

---

packages/opc-styles/package.json
packages/opc-styles/typography/_headings.scss
packages/opc-styles/variables/_1-definitions.scss

Adds the global fontSize and fontWeight.

---

README.md
generator/generator-opc-generator/generators/app/templates/demo/index.html
generator/generator-opc-generator/generators/app/templates/package.json
generator/generator-opc-generator/generators/app/templates/src/_style.scss
generator/generator-opc-generator/generators/app/templates/tsconfig.json
package-lock.json
package.json

- Added opc-styles by default
- Upgraded opc-styles and added as default styles

fix(#30) - Create new command and add packages to root package.json and few other fixes

---

packages/opc-header/.gitignore
packages/opc-header/LICENSE
packages/opc-header/README.md
packages/opc-header/declaration.d.ts
packages/opc-header/demo/index.html
packages/opc-header/jest.config.js
packages/opc-header/package-lock.json
packages/opc-header/package.json
packages/opc-header/src/opc-header.scss
packages/opc-header/src/opc-header.ts
packages/opc-header/test/opc-header.test.ts
packages/opc-header/tsconfig.json
packages/opc-header/webpack.config.js

https://projects.engineering.redhat.com/browse/ONEPLAT-255
A standardized web component based on Lit Element for Red Hat One Platform Header that uses Patternfly Breadcrumb and Links as button HTML component
No
<details>
</details>

feat(ONEPLAT-255): opc-header component

---

.github/workflows/codeql-analysis.yml
README.md

Resolves #50 
No
<details>
</details>

chore(#50): Setup Code Scanning and LGTM Shield

---

packages/opc-header/demo/index.html
packages/opc-header/src/opc-header.ts

Fixes the alerts from lgtm bot
No

fix(lgtm): fixes LGTM alerts

---

generator/generator-opc-generator/generators/app/templates/README.md

Improved the README for the generator
No
NA

fix(#56) - Add usage guide in Generator README

---

generator/generator-opc-generator/generators/app/templates/_.npmignore

fix/#69 - Add src, test and demo to .npmignore in generator

---

generator/generator-opc-generator/generators/app/templates/package.json
generator/generator-opc-generator/package.json

Added main and bumped the minor version for the generator
No

fix(#58) - Adding main to generator package.json and bump version for generator

---

generator/generator-opc-generator/generators/app/index.js
generator/generator-opc-generator/generators/app/templates/README.md
generator/generator-opc-generator/package-lock.json

Fixed regex and added demo/index.html to _.copySingle also Fixed README errors
No

fix(#111) - The generator is not scaffolding accurate component files

---

packages/opc-back-to-top/.npmignore
packages/opc-back-to-top/LICENSE
packages/opc-back-to-top/README.md
packages/opc-back-to-top/declaration.d.ts
packages/opc-back-to-top/demo/index.html
packages/opc-back-to-top/jest.config.js
packages/opc-back-to-top/package-lock.json
packages/opc-back-to-top/package.json
packages/opc-back-to-top/src/opc-back-to-top.scss
packages/opc-back-to-top/src/opc-back-to-top.ts
packages/opc-back-to-top/test/opc-back-to-top.test.ts
packages/opc-back-to-top/tsconfig.json
packages/opc-back-to-top/webpack.config.js

It is back to top web component based on lit element that can be used in other application, its main functionality to take user in starting of screen or top of screen.
No
<details>
</details>

Feat(/#265):- Back to top component.

---

packages/opc-back-to-top/src/opc-back-to-top.scss

There was some unused code in back to top removing that code in this PR.
<details>
</details>

Bug/(#792):-Remove unused code

---

packages/opc-timeline/README.md
packages/opc-timeline/package-lock.json
packages/opc-timeline/package.json

Changed the README for angular support
No

fix(#155) - Current-step-index not working in angular in opc-timeline

---

packages/opc-back-to-top/package.json
packages/opc-back-to-top/webpack.config.js
packages/opc-footer/package.json
packages/opc-footer/webpack.config.js
packages/opc-header/package.json
packages/opc-header/webpack.config.js
packages/opc-timeline/package.json
packages/opc-timeline/webpack.config.js

Added webpack serve in all components
No

fix(#165) - Change components package.json from webpack-dev-server to webpack-serve

---

packages/opc-input-chip/.npmignore
packages/opc-input-chip/LICENSE
packages/opc-input-chip/README.md
packages/opc-input-chip/declaration.d.ts
packages/opc-input-chip/demo/index.html
packages/opc-input-chip/jest.config.js
packages/opc-input-chip/package-lock.json
packages/opc-input-chip/package.json
packages/opc-input-chip/src/opc-input-chip.scss
packages/opc-input-chip/src/opc-input-chip.ts
packages/opc-input-chip/test/opc-input-chip.test.ts
packages/opc-input-chip/tsconfig.json
packages/opc-input-chip/webpack.config.js

Added opc-input-chip component.

---

packages/opc-input-chip/package.json
packages/opc-input-chip/webpack.config.js

updated webpack config and npm script

---

packages/opc-timeline/package-lock.json
packages/opc-timeline/package.json
packages/opc-timeline/src/opc-timeline.scss
packages/opc-timeline/src/opc-timeline.ts

opcTimeline - Fixed the issue with timeline width and also the active being small
No
https://user-images.githubusercontent.com/12994292/106628802-2f706580-65a0-11eb-8867-891a0c8ee64e.mov

fix(#201) - The timeline component doesn't render the horizontal line in the compact version

---

packages/opc-feedback/README.md

Adds Prerequisites to readme file.

---

packages/opc-feedback/package-lock.json
packages/opc-feedback/package.json
packages/opc-feedback/src/opc-feedback.ts

Included the categorization of input from component based on the modal selection
No
N/A

838 - Included the categorization of input from component based on the modal selection

---

packages/opc-feedback/package.json
packages/opc-feedback/src/opc-feedback.ts

Fixed the Url Validations for the component
N/A

838 - Included the URL Validations for the stack

---

package-lock.json
packages/opc-back-to-top/package-lock.json
packages/opc-feedback/package-lock.json
packages/opc-feedback/webpack.config.js
packages/opc-header/package-lock.json
packages/opc-input-chip/package-lock.json
packages/opc-timeline/package-lock.json

Tested all of the components and the generator
- Tested all of the packages and generator
- No

chore(#282) - Fix the renovate errors and test the generator and all the packages

---

renovate.json

- Changed the renovate config for monthly updates
- No

chore(#297) - Configure Renovate PR bot to send updates monthly

---

.storybook/main.js
.storybook/preview.js
package-lock.json
package.json
packages/opc-back-to-top/demo/opc-back-to-top.stories.js
packages/opc-feedback/demo/opc-feedback.stories.js
packages/opc-footer/demo/opc-footer.stories.js
packages/opc-header/demo/opc-header.stories.js
packages/opc-input-chip/demo/opc-input-chip.stories.js
stories/Introduction.stories.mdx

-  Fixed storybook supporting webpack version and added readme to storybooks
No

chore(#306) - Fix changes for storybook caused by renovate PR

---

packages/opc-comment-input/.npmignore
packages/opc-comment-input/LICENSE
packages/opc-comment-input/README.md
packages/opc-comment-input/declaration.d.ts
packages/opc-comment-input/demo/index.html
packages/opc-comment-input/jest.config.js
packages/opc-comment-input/package-lock.json
packages/opc-comment-input/package.json
packages/opc-comment-input/src/opc-comment-input.scss
packages/opc-comment-input/src/opc-comment-input.ts
packages/opc-comment-input/test/opc-comment-input.test.ts
packages/opc-comment-input/tsconfig.json
packages/opc-comment-input/webpack.config.js

No
<details>
Default view:
and, Adding the text to comment input it activates the comment button.
comment list component:
</details>

Added the opc-comment-input and opc-comment-list component.

---

.github/workflows/notify-fork.yml
.github/workflows/notify-main.yml

n/a
change notify workflow repo
No
N/a
<details>
</details>
n/a

chore: change notify workflow repo

---

packages/opc-comment-input/demo/opc-comment-input.stories.js

added storybook for opc-comment-input component.

---

docs/STYLE-GUIDELINE.md

hot-fix: added style guideline

hot-fix: Create STYLE-GUIDELINE.md

---

packages/opc-back-to-top/package-lock.json
packages/opc-back-to-top/package.json

The dependence has been updated to "lit"
Old Dependency 
"lit-element": "2.5.1",
"lit-html": "1.4.1"
New Dependency **
"lit": "^2.0.0-rc.2",
The lit-element and lit-html are combined into one package called lit.
Therefore we (Deepesh Nair  & I) need to update every component & test out the component.

chore: updated the lit dependency.

---

generator/generator-opc-generator/generators/app/templates/package.json

- Added lit and removed lit-html for dependency-update
- No

Dependency update for lit 2.0 for generator

---

packages/opc-input-chip/package-lock.json
packages/opc-input-chip/package.json

- Remove lit-html and add lit 2.0
- No

Dependency update for lit 2.0 for input-chip

---

packages/opc-timeline/package-lock.json
packages/opc-timeline/package.json

- Remove lit-html and add lit 2.0
- No

Dependency update lit 2.0 for timeline 

---

packages/opc-footer/package-lock.json
packages/opc-footer/package.json

The dependence has been updated to "lit"
Old Dependency 
"lit-element": "2.5.1",
"lit-html": "1.4.1"
New Dependency **
"lit": "^2.0.0-rc.2",
The lit-element and lit-html are combined into one package called lit.
Therefore we (Deepesh Nair  & I) need to update every component & test out the component.

updated opc-footer with lit dependency.

---

packages/opc-comment-input/package-lock.json
packages/opc-comment-input/package.json

The dependence has been updated to "lit"
Old Dependency 
"lit-element": "2.5.1",
"lit-html": "1.4.1"
New Dependency **
"lit": "^2.0.0-rc.2",
The lit-element and lit-html are combined into one package called lit.
Therefore we (Deepesh Nair  & I) need to update every component & test out the component.

updated lit dependency.

---

packages/opc-feedback/package-lock.json
packages/opc-feedback/package.json
packages/opc-feedback/src/opc-feedback.ts

Included the polyfills for the support in firefox for this component and updated to lit
No
<details>
</details>

fix:1303 - Included dialog-polyfill for the support in firefox browser and updated to lit

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
generator/generator-opc-generator/generators/app/templates/package.json
package-lock.json
package.json
packages/opc-back-to-top/package-lock.json
packages/opc-back-to-top/package.json
packages/opc-comment-input/package-lock.json
packages/opc-comment-input/package.json
packages/opc-feedback/package-lock.json
packages/opc-feedback/package.json
packages/opc-footer/package-lock.json
packages/opc-footer/package.json
packages/opc-header/package-lock.json
packages/opc-header/package.json
packages/opc-input-chip/package-lock.json
packages/opc-input-chip/package.json
packages/opc-styles/package.json
packages/opc-timeline/package-lock.json
packages/opc-timeline/package.json

- Added test and build automation for all the components
- Added lerna cmds
- No
- N/A

Fix/#351 - Add test and build automation for all the components

---

generator/generator-opc-generator/generators/app/templates/src/_index.ts

- Updated the generator code to lit.20
- No
N/A

fix(#355) - Update the generator code

---

package.json

- Reducing the concurrency to 1
No

Update package.json with concurrency set to 1

---

packages/opc-menu-drawer/README.md
packages/opc-menu-drawer/demo/index.html
packages/opc-menu-drawer/demo/opc-menu-drawer.stories.js
packages/opc-menu-drawer/src/opc-menu-drawer.scss
packages/opc-menu-drawer/src/opc-menu-drawer.ts
packages/opc-menu-drawer/test/opc-menu-drawer.test.ts
packages/opc-notification-drawer/README.md
packages/opc-notification-drawer/demo/index.html
packages/opc-notification-drawer/demo/opc-notification-drawer.stories.js
packages/opc-notification-drawer/src/opc-notification-drawer.scss
packages/opc-notification-drawer/src/opc-notification-drawer.ts
packages/opc-notification-drawer/test/opc-notification-drawer.test.ts

1332
1. Inspired from patternfly-elements [modal component api](https://patternflyelements.org/components/modal/).
2. Ease to use with ssi component.
3. Updated documentation and test
Yes
No ui change only business logic change.

Changed opc-menu-drawer and opc-notification-drawer components methods for better use

---

packages/opc-footer/README.md
packages/opc-footer/demo/index.html
packages/opc-footer/package-lock.json
packages/opc-footer/package.json
packages/opc-footer/src/opc-footer.scss
packages/opc-footer/src/opc-footer.ts

Added flat attribute to remove cube illustration.

Added flat attribute to remove cube illustration.

---

.github/workflows/storybook-build-deploy.yml

- Added storybook deployment yml
- No
N/A

fix(storybook-build-deploy) - Add storybook deploy on merge

---

.github/workflows/storybook-build-deploy.yml

fix(storybook-deploy-hotfix) - Fix for multiple run requests

---

.github/workflows/storybook-build-deploy.yml

- Added both commands 
- No
<!

fix(storybook-hotfix) - Storybook deploy workflow

---

.github/workflows/storybook-build-deploy.yml

ci: fixed ci cd

---

packages/opc-nav/README.md
packages/opc-nav/demo/index.html
packages/opc-nav/package-lock.json
packages/opc-nav/package.json
packages/opc-nav/src/opc-nav-search.scss
packages/opc-nav/src/opc-nav.scss
packages/opc-nav/src/opc-nav.ts
packages/opc-nav/test/opc-nav.test.ts

1568
1. Implemented new opc-nav design
No
<details>
</details>

feat(1568): implemented new opc-nav design

---

packages/opc-styles/package-lock.json
packages/opc-styles/package.json
packages/opc-styles/typography/_base.scss

1. Fixed invalid font name in opc-styles
No
<details>
</details>

hotfix: opc-styles - fixed invalid font name

---

packages/opc-menu-drawer/README.md
packages/opc-menu-drawer/declaration.d.ts
packages/opc-menu-drawer/demo/index.html
packages/opc-menu-drawer/package-lock.json
packages/opc-menu-drawer/package.json
packages/opc-menu-drawer/src/opc-menu-drawer.scss
packages/opc-menu-drawer/src/opc-menu-drawer.ts

1. Changed search to top
2. Fixed font issues
No
<details>
</details>

feat: changed search style in opc-menu-drawer

---

packages/opc-feedback/README.md
packages/opc-feedback/demo/index.html
packages/opc-feedback/package-lock.json
packages/opc-feedback/package.json
packages/opc-feedback/src/opc-feedback.ts
packages/opc-feedback/test/opc-feedback.test.ts
packages/opc-feedback/webpack.config.js

- fixes #801
Fixes #801 
1. Made `spa` and `docs` 
2. Introduced a new attribute `summaryLimit` so that feedback/bug summary is limited.
3. Fixed the <textarea/> state was not getting reset.
4. User can create `onSubmit` function on `opc-feedback` element, which can be used to validate api calls
No
<details>
</details>

feat(feedback): Addressing issues in OPC Feedback Component

---

packages/opc-feedback/package-lock.json
packages/opc-feedback/package.json
packages/opc-feedback/src/opc-feedback.ts

Added error handling for callback function.
No

fix(feedback): Added error handling on callback function

---

packages/opc-feedback/README.md
packages/opc-feedback/package-lock.json
packages/opc-feedback/package.json
packages/opc-feedback/src/opc-feedback.scss

Introduced a dark theme mode for feedback component.
[Screencast from 2024-06-10 18-13-16.webm](https://github.com/1-Platform/op-components/assets/42431299/6b3e143e-48bf-4723-8cd9-6c1c059eff4b)
[Screencast from 2024-06-10 18-14-13.webm](https://github.com/1-Platform/op-components/assets/42431299/088f3ae6-6972-4f31-92ce-a04f978bb64e)
No
<details>
</details>

feat(DEE-1103): added dark theme to feedback web component

---

packages/opc-feedback/package-lock.json
packages/opc-feedback/package.json
packages/opc-feedback/src/opc-feedback.ts

Removed a scenario where only in blue theme the beetle icon was visible
No
</details>

Removed a scenario where only in blue theme the beetle icon was visible
